language: node_js
node_js:
  - 13

services:
  - docker
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed .
  - docker tag simple-node alexanderpavlak/udagram-api-feed:latest
  - docker build -t udagram-api-user .
  - docker tag simple-node alexanderpavlak/udagram-api-user:latest
  - docker build -t udagram-frontend .
  - docker tag simple-node alexanderpavlak/udagram-frontend:latest
  - docker build -t reverseproxy .
  - docker tag simple-node alexanderpavlak/reverseproxy:latest
  

  after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alexanderpavlak/udagram-api-feed:v1
  - docker push alexanderpavlak/udagram-api-user:v1
  - docker push alexanderpavlak/udagram-frontend:v1
  - docker push alexanderpavlak/reverseproxy:v1